const ROOT = path self | path dirname | path dirname
const START = "; @generated by scripts/queries.nu; do not edit below."
const END = "; @end generated Roblox types"
const CLASSES = "content/en-us/reference/engine/classes"
const DATATYPES = "content/en-us/reference/engine/datatypes"
const LICENSE = "LICENSE"

def spec-path [] {
  $ROOT | path join "spec" "roblox-types.json"
}

def query-path [] {
  $ROOT | path join "queries" "highlights.scm"
}

def fail [msg: string] {
  error make { msg: $msg }
}

def git-value [repository: path, arguments: list<string>] {
  let result = (^git -C $repository ...$arguments | complete)

  if $result.exit_code != 0 {
    fail ($result.stderr | str trim)
  }

  $result.stdout | str trim
}

def render-types [types: list<string>] {
  let quote = char dq
  let rows = (
    $types
    | uniq
    | sort
    | chunks 5
    | each {|row|
        let values = ($row | each {|name| $"($quote)($name)($quote)"} | str join " ")
        $"    ($values)"
      }
  )

  [
    "((type_reference name: (identifier) @type.builtin)"
    "  (#any-of? @type.builtin"
    ...$rows
    "  ))"
  ] | str join (char newline)
}

def generated-query [] {
  let spec = open (spec-path)
  let body = render-types $spec.types
  $"; Source: Roblox/creator-docs ($spec.source.revision) (($spec.source.date))\n($body)"
}

def expected-query [] {
  let actual = open --raw (query-path)
  let start = $actual | split row $START

  if ($start | length) != 2 {
    fail $"expected exactly one generated start marker in (query-path)"
  }

  let end = $start.1 | split row $END

  if ($end | length) != 2 {
    fail $"expected exactly one generated end marker in (query-path)"
  }

  $"($start.0)($START)\n(generated-query)\n($END)($end.1)"
}

def sync [] {
  expected-query | save --force (query-path)
  print $"Generated (query-path)"
}

def "main sync" [] {
  sync
}

def "main check" [] {
  let path = query-path
  let actual = open --raw $path
  let expected = expected-query

  if $actual != $expected {
    fail $"generated output is stale: ($path); run `nu scripts/queries.nu sync`"
  }

  print "Generated queries are current"
}

def "main update" [creator_docs: path] {
  let checkout = $creator_docs | path expand
  let class_dir = $checkout | path join $CLASSES
  let datatype_dir = $checkout | path join $DATATYPES

  if not ($class_dir | path exists) {
    fail $"Creator Docs class directory does not exist: ($class_dir)"
  }

  if not ($datatype_dir | path exists) {
    fail $"Creator Docs datatype directory does not exist: ($datatype_dir)"
  }

  let paths = (
    (glob $"($class_dir | str replace --all '\' '/')/*.yaml")
    | append (glob $"($datatype_dir | str replace --all '\' '/')/*.yaml")
  )
  let types = (
    $paths
    | each {|path| $path | path parse | get stem}
    | where {|name| $name =~ '^[A-Za-z_][A-Za-z0-9_]*$'}
    | uniq
    | sort
  )

  let snapshot = {
    source: {
      repository: "https://github.com/Roblox/creator-docs"
      revision: (git-value $checkout ["log" "-1" "--format=%H" "--" $CLASSES $DATATYPES])
      date: (git-value $checkout ["log" "-1" "--format=%cs" "--" $CLASSES $DATATYPES])
      directories: [$CLASSES $DATATYPES]
    }
    types: $types
  }

  let directory = $ROOT | path join "spec"
  mkdir $directory
  let json = $snapshot | to json --indent 2
  $"($json)\n" | save --force (spec-path)
  cp --force ($checkout | path join $LICENSE) ($directory | path join $LICENSE)
  sync
  print $"Imported ($types | length) Roblox types from ($checkout)"
}

def main [] {
  fail "usage: nu scripts/queries.nu <check|sync|update <creator-docs>>"
}
