use std/assert

const ROOT: string = path self | path dirname | path dirname
const START: string = "; @generated by scripts/queries.nu; do not edit below."
const END: string = "; @end generated Roblox types"
const CLASSES: string = "content/en-us/reference/engine/classes"
const DATATYPES: string = "content/en-us/reference/engine/datatypes"
const LICENSE: string = "LICENSE"

def query-targets []: nothing -> list<record<path: string, local_aware: bool>> {
    [
        {
            path: ($ROOT | path join queries highlights.scm)
            local_aware: true
        }
        {
            path: ($ROOT | path join queries neovim highlights.scm)
            local_aware: false
        }
    ]
}

def git-value [repository: path, ...arguments: string]: nothing -> string {
    let result: record = git -C $repository ...$arguments | complete
    assert ($result.exit_code == 0) ($result.stderr | str trim)
    $result.stdout | str trim
}

def render-names [...names: string]: nothing -> list<string> {
    let quote: string = char dq

    $names
    | uniq
    | sort
    | chunks 5
    | each {|row|
        let values: string = $row | each {|name| $"($quote)($name)($quote)" } | str join " "
        $"    ($values)"
      }
}

def render-types [...types: string]: nothing -> string {
    let rows: list<string> = render-names ...$types

    [
        "((type_reference name: (identifier) @type.builtin)"
        "  (#any-of? @type.builtin"
        ...$rows
        "  ))"
    ] | str join (char newline)
}

def render-value-types [local_aware: bool, ...types: string]: nothing -> string {
    let rows: list<string> = render-names ...$types

    let end: list<string> = if $local_aware {
        ["  (#is-not? local))"]
    } else {
        [")"]
    }

    [
        "(["
        "  (field_expression table: (identifier) @type.builtin)"
        "  (method_call_expression receiver: (identifier) @type.builtin)"
        "  (type_instantiation_expression receiver: (identifier) @type.builtin)"
        "]"
        "  (#any-of? @type.builtin"
        ...$rows
        "  )"
        ...$end
    ] | str join (char newline)
}

def generated-query [local_aware: bool]: nothing -> string {
    let spec: record = open ($ROOT | path join spec roblox-types.json)

    let types: list<string> = $spec.types | each {|name| $name | into string }
    let value_types: list<string> = $spec.value_types | each {|name| $name | into string }

    let body: string = [
        (render-types ...$types)
        (render-value-types $local_aware ...$value_types)
    ] | str join "\n\n"

    $"; Source: Roblox/creator-docs ($spec.source.revision) (($spec.source.date))\n($body)"
}

def expected-query [path: path, local_aware: bool]: nothing -> string {
    let actual: string = open --raw $path

    let start: list<string> = $actual | split row $START

    assert (($start | length) == 2) $"expected exactly one generated start marker in ($path)"

    let end: list<string> = $start.1? | split row $END

    assert (($end | length) == 2) $"expected exactly one generated end marker in ($path)"

    $"($start.0?)($START)\n(generated-query $local_aware)\n($END)($end.1?)"
}

def sync []: nothing -> nothing {
    for target in (query-targets) {
        expected-query $target.path $target.local_aware | save --force $target.path
    }
}

def "main sync" []: nothing -> nothing {
    sync
    print "Generated queries"
}

def "main check" []: nothing -> nothing {
    for target in (query-targets) {
        let actual: string = open --raw $target.path
        let expected: string = expected-query $target.path $target.local_aware
        assert ($actual == $expected) $"generated output is stale: ($target.path); run `nu scripts/queries.nu sync`"
    }

    print "Generated queries are current"
}

def "main update" [
    creator_docs: path # Creator Docs checkout to import type metadata from.
]: nothing -> nothing {
    let checkout: path = $creator_docs | path expand
    let class_dir: path = $checkout | path join $CLASSES
    let datatype_dir: path = $checkout | path join $DATATYPES

    assert ($class_dir | path exists) $"Creator Docs class directory does not exist: ($class_dir)"
    assert ($datatype_dir | path exists) $"Creator Docs datatype directory does not exist: ($datatype_dir)"

    let class_paths: list<path> = glob $"($class_dir | str replace --all (char --unicode 5c) /)/*.yaml"
    let datatype_paths: list<path> = glob $"($datatype_dir | str replace --all (char --unicode 5c) /)/*.yaml"

    let types: list<string> = (
    $class_paths
    | append $datatype_paths
    | each {|path| $path | path parse | get stem }
    | where $it =~ '^[A-Za-z_][A-Za-z0-9_]*$'
    | uniq
    | sort
  )

    let value_types: list<string> = (
    $datatype_paths
    | each {|path|
        let document: record = open $path

        let constructors: list = $document.constructors? | default []
        let constants: list = $document.constants? | default []
        let functions: list = $document.functions? | default []

        if (($constructors | is-not-empty) or ($constants | is-not-empty) or ($functions | is-not-empty)) {
            $document.name | into string
        }
      }
    | compact
    # Creator Docs names the global Enum container `Enums`.
    | append Enum
    | where $it =~ '^[A-Za-z_][A-Za-z0-9_]*$'
    | uniq
    | sort
  )

    let snapshot: record = {
        source: {
            repository: $"https://github.com/Roblox/creator-docs"

            revision: (
                git-value $checkout log "-1" "--format=%H" "--" $CLASSES $DATATYPES
            )

            date: (
                git-value $checkout log "-1" "--format=%cs" "--" $CLASSES $DATATYPES
            )

            directories: [$CLASSES $DATATYPES]
        }

        types: $types
        value_types: $value_types
    }

    let directory: path = $ROOT | path join spec

    mkdir $directory

    let json: string = $snapshot | to json --indent 2

    $"($json)\n" | save --force ($ROOT | path join spec roblox-types.json)
    cp --force ($checkout | path join $LICENSE) ($directory | path join $LICENSE)

    sync
    print $"Imported ($types | length) Roblox types from ($checkout)"
}

def "main copy" [
    editor: string # Query set: helix, mitos, neovim, or zed.
    runtime: path # Editor runtime root containing queries/.
]: nothing -> nothing {
    assert ($editor in [helix mitos neovim zed]) $"Unknown editor: ($editor)"

    let variant: string = if $editor == "mitos" { "helix" } else { $editor }

    let source: path = $ROOT | path join queries $variant
    let queries: list<path> = glob $"($source | str replace --all (char --unicode 5c) /)/*.scm"
    let target: path = $runtime | path expand | path join queries luau

    mkdir $target
    cp --force ...$queries $target
    print $"Copied ($editor) queries to ($target)"
}

def main [] {
    assert false "usage: nu scripts/queries.nu <check|sync|update <creator-docs>|copy <editor> <runtime>>"
}
