const ROOT: string = path self | path dirname | path dirname
const START: string = "; @generated by scripts/queries.nu; do not edit below."
const END: string = "; @end generated Roblox types"
const CLASSES: string = "content/en-us/reference/engine/classes"
const DATATYPES: string = "content/en-us/reference/engine/datatypes"
const LICENSE: string = "LICENSE"

def spec-path []: nothing -> string {
    $ROOT | path join spec roblox-types.json
}

def query-path []: nothing -> string {
    $ROOT | path join queries highlights.scm
}

def fail [msg: string]: nothing -> error {
    error make {
        msg: $msg
        label: {
            text: $msg
            span: (metadata $msg).span
        }
    }
}

def git-value [repository: path, ...arguments: string]: nothing -> string {
    let result: record = git -C $repository ...$arguments | complete

    if $result.exit_code != 0 {
        fail ($result.stderr | str trim)
    }

    $result.stdout | str trim
}

def render-types [...types: string]: nothing -> string {
    let quote: string = char dq
    let rows: list<string> = (
    $types
    | uniq
    | sort
    | chunks 5
    | each {|row|
        let values: string = $row | each {|name| $"($quote)($name)($quote)" } | str join " "
        $"    ($values)"
      }
  )

    [
        "((type_reference name: (identifier) @type.builtin)"
        "  (#any-of? @type.builtin"
        ...$rows
        "  ))"
    ] | str join (char newline)
}

def generated-query []: nothing -> string {
    let spec: record = try {
        open (spec-path)
    } catch {|error| fail $"Failed to read the Roblox type snapshot: ($error.msg)" }
    let types: list<string> = $spec.types | each {|name| $name | into string }
    let body: string = render-types ...$types
    $"; Source: Roblox/creator-docs ($spec.source.revision) (($spec.source.date))\n($body)"
}

def expected-query []: nothing -> string {
    let actual: string = try {
        open --raw (query-path)
    } catch {|error| fail $"Failed to read the highlight query: ($error.msg)" }
    let start: list<string> = $actual | split row $START

    if ($start | length) != 2 {
        fail $"expected exactly one generated start marker in (query-path)"
    }

    let end: list<string> = $start.1? | split row $END

    if ($end | length) != 2 {
        fail $"expected exactly one generated end marker in (query-path)"
    }

    $"($start.0?)($START)\n(generated-query)\n($END)($end.1?)"
}

def sync []: nothing -> nothing {
    try {
        expected-query | save --force (query-path)
    } catch {|error| fail $"Failed to write the highlight query: ($error.msg)" }
}

def "main sync" []: nothing -> nothing {
    sync
    print $"Generated (query-path)"
}

def "main check" []: nothing -> nothing {
    let path: string = query-path
    let actual: string = try {
        open --raw $path
    } catch {|error| fail $"Failed to read the highlight query: ($error.msg)" }
    let expected: string = expected-query

    if $actual != $expected {
        fail $"generated output is stale: ($path); run `nu scripts/queries.nu sync`"
    }

    print "Generated queries are current"
}

def "main update" [
    creator_docs: path # Creator Docs checkout to import type metadata from.
]: nothing -> nothing {
    let checkout: path = $creator_docs | path expand
    let class_dir: path = $checkout | path join $CLASSES
    let datatype_dir: path = $checkout | path join $DATATYPES

    if not ($class_dir | path exists) {
        fail $"Creator Docs class directory does not exist: ($class_dir)"
    }

    if not ($datatype_dir | path exists) {
        fail $"Creator Docs datatype directory does not exist: ($datatype_dir)"
    }

    let paths: list<path> = (
    (glob $"($class_dir | str replace --all (char backslash) /)/*.yaml")
    | append (glob $"($datatype_dir | str replace --all (char backslash) /)/*.yaml")
  )
    let types: list<string> = (
    $paths
    | each {|path| $path | path parse | get stem }
    | where $it =~ '^[A-Za-z_][A-Za-z0-9_]*$'
    | uniq
    | sort
  )

    let snapshot: record = {
        source: {
            repository: $"https://github.com/Roblox/creator-docs"
            revision: (
                git-value $checkout log "-1" "--format=%H" "--" $CLASSES $DATATYPES
            )
            date: (
                git-value $checkout log "-1" "--format=%cs" "--" $CLASSES $DATATYPES
            )
            directories: [$CLASSES $DATATYPES]
        }
        types: $types
    }

    let directory: path = $ROOT | path join spec
    try {
        mkdir $directory
    } catch {|error| fail $"Failed to create the snapshot directory: ($error.msg)" }
    let json: string = $snapshot | to json --indent 2
    try {
        $"($json)\n" | save --force (spec-path)
    } catch {|error| fail $"Failed to write the Roblox type snapshot: ($error.msg)" }
    try {
        cp --force ($checkout | path join $LICENSE) ($directory | path join $LICENSE)
    } catch {|error| fail $"Failed to copy the Creator Docs license: ($error.msg)" }
    sync
    print $"Imported ($types | length) Roblox types from ($checkout)"
}

def main []: nothing -> error {
    fail "usage: nu scripts/queries.nu <check|sync|update <creator-docs>>"
}
